# Use a node base image
FROM node:18.12.0

# Set the working directory inside the container for the client
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the entire client directory to the container
COPY . .

# Specify the command to start the React app in development
CMD ["npm", "start"]
