version: '3'
services:
  social-client-prod:
    image: ${REPO_NAME}:client-${ENV}-latest
    env_file: ${ENV_FILE}
    # restart: unless-stopped # restart on failure
    stdin_open: true # allow input from terminal
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes: # to store tsl certificate configuration
      - ${TLS_CERT_FILE}:/keys/tls_cert.pem
      - ${TLS_KEY_FILE}:/keys/tls_key.pem
  
  social-api-prod:
    image: ${REPO_NAME}:server-${ENV}-latest
    env_file: ${ENV_FILE}
    # restart: unless-stopped
    ports:
      - "${API_PORT}:${API_PORT}"

volumes:
  caddy-data:
    driver: local
  caddy-config:
    driver: local

