version: '3'
services:
  bullhorn-client-prod:
    image: bullhorn-client-prod
    restart: unless-stopped # restart on failure
    stdin_open: true # allow input from terminal
    ports:
      - "80:80"
      - "443:443"
  bullhorn-api-prod:
    image: api-server-prod
    env_file: ./server/prod.env
    restart: unless-stopped
    ports:
      - "4000:4000"
  nginx:
    image: bullhorn-nginx
    environment:
      - API_PORT=4000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount NGINX configuration
    ports:
      - "80:80"
    depends_on:
      - bullhorn-client-prod
      - api-server-prod

