version: '3'
services:
  social-client-prod:
    image: ${DOCKER_USERNAME}/social-app:client-${ENV}-latest
    env_file: ${ENV_FILE}
    # restart: unless-stopped # restart on failure
    stdin_open: true # allow input from terminal
    volumes:
      - client_build:/usr/src/app/build  # Mount built client files from the named volume
  caddy:
    image: caddy:2.4.3-alpine
    stdin_open: true # allow input from terminal
    volumes:
      - ${TLS_CERT_FILE}:/certs/tls_cert.pem  # Mount SSL/TLS certificate
      - ${TLS_KEY_FILE}:/certs/tls_key.pem
      - ./client/Caddyfile.${ENV}:/etc/caddy/Caddyfile
      - client_build:/srv
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    depends_on:
      - social-client-prod
    command: ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile", "--log", "stdout", "--log-level", "debug"]
  # social-api-prod:
  #   image: ${DOCKER_USERNAME}/social-app:server-${ENV}-latest
  #   env_file: ${ENV_FILE}
  #   # restart: unless-stopped
  #   ports:
  #     - "${API_PORT}:${API_PORT}"
volumes:
  client_build: {}

