version: '3'
services:
  social-client-prod:
    image: social-app:client-${ENV}-latest
    env_file: ./client/.env.production
    environment:
      - REACT_APP_CLIENT_URL=${REACT_APP_CLIENT_URL}
    restart: unless-stopped # restart on failure
    stdin_open: true # allow input from terminal
    ports:
      - "80:80"
      - "443:443"
    volumes: # to store tsl certificate configuration
      - caddy-data:/data
      - caddy-config:/config
  social-api-prod:
    image: social-app:server-${ENV}-latest
    env_file: ./server/.env.production
    environment:
      - CLIENT_URL=${CLIENT_URL}
    restart: unless-stopped
    ports:
      - "4000:4000"
volumes:
  caddy-data:
    driver: local
  caddy-config:
    driver: local

