export enum Dep {
  App = 'app',
  isAuthenticated = 'isAuthenticated',
  HttpServer = 'httpServer',
  HashService = 'hashService',
  JWTService = 'jwtService',
  FirebaseJWTService = 'firebaseJWTService',
  SocketService = 'socketService',
  DaoErrorHandler = 'daoErrorHandler',
  UserDao = 'userDao',
  PostDao = 'postDao',
  FollowDao = 'followDao',
  LikeDao = 'likeDao',
  MessageDao = 'messageDao',
  NotificationDao = 'notificationDao',
  BookmarkDao = 'bookmarkDao',
  UserController = 'userController',
  AuthController = 'authController',
  PostController = 'postController',
  BookmarkController = 'bookmarkController',
  FollowController = 'followController',
  LikeController = 'likeController',
  MessageController = 'messageController',
  NotificationController = 'notificationController',
  SearchController = 'searchController',
}
