# Use a node base image
FROM node:18.12.0

# Set the working directory inside the container for the server
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Install nodemon globally for hot reloading (optional)
RUN npm install -g nodemon

# Install ts-node globally for running typescript files (optional)
RUN npm install -g ts-node

# Copy the entire server directory to the container
COPY . .

EXPOSE 4000

RUN chmod +x startdev.sh
# Specify the command to start the server with nodemon for hot reloading
CMD ["./startdev.sh"]
