FROM node:18.12.0

WORKDIR /usr/src/server

#src to working dir
COPY ./package.json ./ 
COPY ./package-lock.json ./ 

RUN npm install

COPY . . 

RUN npm run build
WORKDIR /usr/src/server/build

EXPOSE 5500

CMD ["npm" , "start"]