# Stage 1: Building the app
FROM node:18.12.0-alpine as builder

WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm install --omit=dev
COPY . .
RUN npm run build

# Stage 2: Running the app
FROM node:18.12.0-alpine

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/package.json /usr/src/app/package-lock.json ./
COPY --from=builder /usr/src/app/build ./build

RUN npm install --only=production

EXPOSE 4000

CMD ["npm", "run", "start"]
