import { FormFieldI } from '../../interfaces/FormFieldI';

export const profileFieldsStore: FormFieldI = {
  name: {
    id: 'name',
    name: 'name',
    type: 'text',
    placeholder: 'name',
    errorMessage:
      "Name should be 3-20 characters and shouldn't include any special character!",
    label: 'name',
    pattern: "^[A-Za-z0-9 ,.'\\-]{3,20}$",
    required: true,
    value: '',
    readOnly: false,
  },
  username: {
    id: 'username',
    name: 'username',
    type: 'text',
    placeholder: 'username (required)',
    errorMessage:
      "Username should be 3-16 characters and shouldn't include any special character.",
    label: 'username',
    pattern: '^[A-Za-z0-9]{3,16}$',
    required: true,
    value: '',
    readOnly: false,
  },
  email: {
    id: 'email',
    name: 'email',
    type: 'text',
    placeholder: 'email',
    errorMessage: 'Enter a valid email address.',
    label: 'email',
    required: true,
    value: '',
    pattern: '^[a-z0-9._%+\\-]+@[a-z0-9.\\-]+\\.[a-z]{2,4}$',
    readOnly: false,
  },
  bio: {
    id: 'bio',
    name: 'bio',
    type: 'text',
    placeholder: 'bio (optional)',
    errorMessage: 'Bio should not exceed 280 characters.',
    label: 'bio',
    pattern: '^.{0,280}$',
    required: false,
    value: '',
    readOnly: false,
  },
  headerImage: {
    id: 'headerImage',
    name: 'headerImage',
    type: 'file',
    placeholder: '',
    errorMessage: '',
    label: 'header image',
    pattern: '',
    required: false,
    value: '',
    readOnly: false,
  },
  profilePhoto: {
    id: 'profilePhoto',
    name: 'profilePhoto',
    type: 'file',
    placeholder: '',
    errorMessage: '',
    label: 'profile photo',
    pattern: '',
    required: false,
    value: '',
    readOnly: false,
  },
  password: {
    id: 'password',
    name: 'password',
    type: 'password',
    placeholder: 'password',
    errorMessage:
      'Password should be 8-20 characters and include at least 1 letter, 1 number and 1 special character!',
    label: 'password',
    pattern: `^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,20}$`,
    required: false,
    value: '',
    readOnly: false,
  },
  confirmPassword: {
    id: 'confirmPassword',
    name: 'confirmPassword',
    type: 'password',
    placeholder: 'confirm password',
    errorMessage: "Passwords don't match!",
    label: 'confirm password',
    required: false,
    pattern: 'password',
    value: '',
    readOnly: false,
  },
};
