import { InputFieldI } from '../../interfaces/InputFieldI';

export const profileFields: InputFieldI = {
  name: {
    id: '0',
    name: 'name',
    type: 'text',
    placeholder: 'name',
    errorMessage:
      "Name should be 3-20 characters and shouldn't include any special character!",
    label: 'name',
    // pattern: "^[A-Za-z0-9 ,.'-]{3,20}$",
    pattern: '.*',
    required: true,
    value: '',
  },
  username: {
    id: '1',
    name: 'username',
    type: 'text',
    placeholder: 'username (required)',
    errorMessage:
      "Username should be 3-16 characters and shouldn't include any special character.",
    label: 'username',
    pattern: '^[A-Za-z0-9]{3,16}$',
    required: true,
    value: '',
  },
  email: {
    id: '2',
    name: 'email',
    type: 'text',
    placeholder: 'email',
    errorMessage: 'Enter a valid email address.',
    label: 'email',
    required: true,
    value: '',
    pattern: '.*',
    // pattern: '[a-z0-9._%+-]+@[a-z0-9.-]+.[a-z]{2,4}$',
  },
  // birthday: {
  //   id: '3',
  //   name: 'birthday',
  //   type: 'date',
  //   placeholder: 'birthday (optional)',
  //   errorMessage: 'Please enter a valid date for birthday.',
  //   label: 'birthday',
  //   required: true,
  //   value: '',
  //   pattern: '',
  // },
  bio: {
    id: '4',
    name: 'bio',
    type: 'text',
    placeholder: 'bio (optional)',
    errorMessage: 'Bio should not exceed 280 characters.',
    label: 'bio',
    pattern: '^.{0,280}$',
    required: false,
    value: '',
  },
  headerImage: {
    id: '5',
    name: 'headerImage',
    type: 'file',
    placeholder: '',
    errorMessage: '',
    label: 'header image',
    pattern: '',
    required: false,
    value: '',
  },
  profilePhoto: {
    id: '6',
    name: 'profilePhoto',
    type: 'file',
    placeholder: '',
    errorMessage: '',
    label: 'profile photo',
    pattern: '',
    required: false,
    value: '',
  },
  password: {
    id: '7',
    name: 'password',
    type: 'password',
    placeholder: 'password',
    errorMessage:
      'Password should be 8-20 characters and include at least 1 letter, 1 number and 1 special character!',
    label: 'password',
    pattern: `^(?=.*[0-9])(?=.*[a-zA-Z])(?=.*[!@#$%^&*])[a-zA-Z0-9!@#$%^&*]{8,20}$`,
    required: false,
    value: '',
  },
};
