name: CD Pipeline

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed
      - success
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Clean existing app directory
        run: |
          rm -rf /home/ec2-user/app
          mkdir /home/ec2-user/app

      - name: Checkout repo
        uses: actions/checkout@v3

      # Move the checked-out repository to the desired directory
      - name: Move repository to target directory
        run: cp -r $GITHUB_WORKSPACE/* /home/ec2-user/app

      - name: Pull client Docker image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/social-app:client-production-latest

      - name: Pull server Docker image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/social-app:client-production-latest

      - name: Stop and remove old client container
        run: |
          sudo docker stop client-production-latest || true
          sudo docker rm client-production-latest || true

      - name: Stop and remove old server container
        run: |
          sudo docker stop server-production-latest || true
          sudo docker rm server-production-latest || true

      - name: Run client and server container with Makefile command
        run: make run-production DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
