name: CD Pipeline

on:
  workflow_run:
    workflows: ['CI Pipe']
    types:
      - completed
      - success

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pull client Docker image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/social-app:client-production-latest

      - name: Pull server Docker image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/social-app:server-production-latest

      - name: Stop and remove old client container
        run: |
          sudo docker stop social-app:client-production-latest || true
          sudo docker rm social-app:client-production-latest || true

      - name: Stop and remove old server container
        run: |
          sudo docker stop social-app:server-production-latest || true
          sudo docker rm social-app:server-production-latest || true

      - name: Run client and server container with Makefile command
        run: make -f Makefile run-production DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
