name: CD Pipeline

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed
      - success
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/ec2-user/buzzcentral
    steps:
      - name: Pull client Docker image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/social-app:client-production-latest

      - name: Pull server Docker image from Docker Hub
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/social-app:client-production-latest

      - name: Stop and remove old client container
        run: |
          sudo docker stop client-production-latest || true
          sudo docker rm client-production-latest || true

      - name: Stop and remove old server container
        run: |
          sudo docker stop server-production-latest || true
          sudo docker rm server-production-latest || true

      - name: Clean existing 'docker' directory
        run: rm -rf "/home/ec2-user/buzzcentral/docker"

      - name: Checkout 'docker' directory
        uses: actions/checkout@v3
        with:
          path: 'docker'

      - name: Run client and server container with Makefile command
        working-directory: './docker'
        run: make -f Makefile run-production DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
