name: CD Pipeline

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed
      - success

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/ec2-user/buzzcentral

    steps:
      - name: Load .env file
        run: |
          set -o allexport
          source .env
          set +o allexport

      - name: Pull client Docker image from Docker Hub
        run: |
          DOCKER_CLIENT_IMAGE="${DOCKER_USERNAME}/social-app:client-production-latest"
          sudo docker pull "$DOCKER_CLIENT_IMAGE"

      - name: Pull server Docker image from Docker Hub
        run: |
          DOCKER_SERVER_IMAGE="${DOCKER_USERNAME}/social-app:server-production-latest"
          sudo docker pull "$DOCKER_SERVER_IMAGE"

      - name: Stop and remove old client container
        run: |
          sudo docker stop client-production-latest || true
          sudo docker rm client-production-latest || true

      - name: Stop and remove old server container
        run: |
          sudo docker stop server-production-latest || true
          sudo docker rm server-production-latest || true

      - name: Run client and server container with Makefile command
        run: make -f compose.prod.yml run-production DOCKER_USERNAME=${DOCKER_USERNAME}
