name: CD Pipeline
on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed
      - success

jobs:
  build:
    runs-on: self-hosted

    # Set up environment variables before defining the working directory
    steps:
      - name: Load .env file
        run: |
          set -o allexport
          source buzzcentral/.env
          set +o allexport

    defaults:
      run:
        working-directory: /home/$EC2_USERNAME/buzzcentral
    steps:
      - name: Clean existing 'docker' directory
        run: rm -rf /home/$EC2_USERNAME/buzzcentral/docker

      - name: Checkout 'docker' directory
        uses: actions/checkout@v3
        with:
          path: 'docker'

      - name: Pull client Docker image from Docker Hub
        run: sudo docker pull $DOCKER_USERNAME/social-app:client-production-latest

      - name: Pull server Docker image from Docker Hub
        run: sudo docker pull $DOCKER_USERNAME/social-app:server-production-latest

      - name: Stop and remove old client container
        run: |
          sudo docker stop client-production-latest || true
          sudo docker rm client-production-latest || true

      - name: Stop and remove old server container
        run: |
          sudo docker stop server-production-latest || true
          sudo docker rm server-production-latest || true

      - name: Run client and server container with Makefile command
        working-directory: ./docker
        run: make -f compose.prod.yml run-production DOCKER_USERNAME=$DOCKER_USERNAME
