name: CI Pipeline

on:
  push:
    branches: [staging]

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Build and push client Docker image
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        # Passing password via stdin for better security, avoiding leaking it in the CLI
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker image for client
        run: |
          make -f Makefile build-client-production DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}

      - name: Build Docker image for server
        run: |
          make -f Makefile build-server-production DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}

      # Push client and server images to Docker Hub
      - name: Push client Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/social-app:client-production-latest

      - name: Push server Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/social-app:server-production-latest
