name: Build, Push to Docker Hub, and Deploy to EC2
on:
  push:
    branches: [staging]

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      # Build and push client Docker image
      - name: Login to Docker Hub
        uses: actions/checkout@v3
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image for client
        run: |
          make -f Makefile build-client-production

      - name: Build Docker image for client
        run: |
          make -f Makefile build-server-production

      # Push client and server images to Docker Hub
      - name: Push client Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/social-app:client

      - name: Push server Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/social-app:server

  # deploy-to-ec2:
  #   name: Deploy to EC2
  #   runs-on: ubuntu-latest
  #   needs: [build-and-push]

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     # Configure AWS credentials for EC2 deployment
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: your-aws-region

  #     # Deploy to EC2 using Docker run command for both client and server
  #     - name: Deploy Client to EC2 using Docker run command
  #       run: |
  #         docker pull your-dockerhub-username/client-image-name:tag
  #         docker run -d -p 80:80 your-dockerhub-username/client-image-name:tag

  #     - name: Deploy Server to EC2 using Docker run command
  #       run: |
  #         docker pull your-dockerhub-username/server-image-name:tag
  #         docker run -d -p 3000:3000 your-dockerhub-username/server-image-name:tag
